# Generated by Django 5.0 on 2024-02-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company_logo')),
                ('description', models.TextField(max_length=40000)),
                ('name', models.CharField(max_length=30)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('threds_link', models.URLField(blank=True, null=True)),
                ('email', models.TextField(blank=True, max_length=200, null=True)),
                ('phone', models.TextField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('androidapp_link', models.URLField(blank=True, null=True)),
                ('iosapp_link', models.URLField(blank=True, null=True)),
                ('call_us', models.CharField(max_length=30)),
                ('email_us', models.CharField(max_length=30)),
            ],
        ),
    ]
